POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe Billing 2",
  "email": "whoiswho_billing2@gmail.com",
  "address": "address",
  "dateOfBirth": "2005-09-01",
  "registeredDate": "2006-02-03"
}