POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "s@gmail.com",
  "address": "123 street",
  "dateOfBirth":"1923-03-01",
  "registeredDate": "1956-01-01"
}